class_name CharacterTraits
extends Resource

static var names: Array[String] = [
	"Alex",
	"Bailey",
	"Charlie",
	"Gray",
	"Harper",
	"Jordan",
	"John",
	"Logan",
	"Nico",
	"Parker",
	"River",
	"Sawyer",
	"Taylor",
	"Tali",
	"Maali",
	"Khairat",
	"Hareem",
	"Jun",
	"Feng",
	"Jiang",
	"Yuki",
	"Haruki",
	"Kai",
	"Kris",
	"Robin",
	"Bjorn"
]

static var titles: Array[String] = [
	"Gambler",
	"Bodyguard",
	"Mafioso",
	"Bartender",
	"Godfather",
	"Hitman",
	"Gunner",
	"Thief",
	"Dealer",
	"Boss",
	"Capo",
	"Don",
	"Spy",
	"Consigliere",
	"Consort",
	"Escort",
	"Guy",
	"Outlaw",
	"Felon",
	"Kingpin",
	"Villain",
	"Thug",
	"Mobster",
	"Hustler",
	"Fugitive",
	"Drunk",
	"Convict",
	"Crook",
	"Tycoon"
]

static var portraits: Array[String] = [
	"res://Assets/Art/Actors/Portraits/bald.png",
	"res://Assets/Art/Actors/Portraits/beard.png",
	"res://Assets/Art/Actors/Portraits/beret.png",
	"res://Assets/Art/Actors/Portraits/bigguy.png",
	"res://Assets/Art/Actors/Portraits/long.png",
	"res://Assets/Art/Actors/Portraits/lookingside.png",
	"res://Assets/Art/Actors/Portraits/mediumhair.png",
	"res://Assets/Art/Actors/Portraits/mustache.png", 
	"res://Assets/Art/Actors/Portraits/player.png",
	"res://Assets/Art/Actors/Portraits/sho.png",
	"res://Assets/Art/Actors/Portraits/short.png",
	"res://Assets/Art/Actors/Portraits/turban.png",
	"res://Assets/Art/Actors/Portraits/woman.png",
]
